  - name: installing dependencies
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - curl
      - gcc
      - memcached
      - rsync
      - sqlite
      - xfsprogs
      - git
      - git-core
      - libffi-dev
      - liberasurecode-dev
      - xinetd
      - python-setuptools
      - python-dev
      - python-simplejson 
      - python-xattr
      - python-eventlet
      - python-greenlet
      - python-netifaces
      - python-pip
      - python-dnspython
      - python-mock
      - python-selinux
      - tree
      - vim
      - make
      - autoconf
      - automake
      - libtool

  - name: install python modules with pip
    pip: name={{ item }} state=present extra_args='--upgrade'
    with_items:
      - tox
      - nose
      - xattr
      - git-review
      - coverage
      - Paste
      - pyudev
      - pip
      - setuptools
      - pyeclib

